- hosts: all
  gather_facts: false
  become: false
  tasks:
  - name: Deploy the service
    k8s:
      state: "{{state|default('present')}}"
      definition: ""
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: "{{state|default('present')}}"
      validate_certs: no
      namespace: default
      definition: ""
